<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InnoClinic.Contracts" Version="1.0.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
    <ProjectReference Include="..\Services.Domain\Services.Domain.csproj" />
	  <InternalVisibleTo Include="Services.Presentation" />
        <InternalVisibleTo Include="Services.Infrastructure" />
	      <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />	  <PackageReference Include="Autofac" Version="9.1.0" />
	  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="14.1.0" />
  </ItemGroup>

</Project>
